[tool.poetry]
name = "projectname"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8,<3.12"
tensorflow = "2.12.0"


[build-system]
requires = ["poetry-core"]
