# fly.toml app configuration file generated for untexifyweb on 2023-05-21T14:24:24-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "untexifyweb"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
